In [1]:
import numpy as np

# Questão 1

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# Questão 2

In [3]:
arr = np.array([1, 2, 3, 4], ndmin=2)
print(arr)

[[1 2 3 4]]


# Questão 3

In [4]:
arr = np.array([1, 2, 3, 4])
print(arr.ndim)

1


# Questão 4

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


# Questão 5

In [6]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[4])

50


# Questão 6

In [7]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr[1, 0])

50


# Questão 7

In [8]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])

50


# Questão 8

In [9]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:5])

[15 20 25 30]


# Questão 9

In [10]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


# Questão 10

In [11]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[1:5:2])

[15 25]
